name: Build APK for Android

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker for Buildozer
        uses: docker/setup-buildx-action@v1

      - name: Build APK
        run: |
          docker build -t kivy-android-app .
          docker run -v $(pwd):/app kivy-android-app
